# Generated by Django 5.2.8 on 2025-12-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aprendices', '0001_initial'),
        ('Computadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uso_computador',
            name='ID_computador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computadores.computador'),
        ),
    ]
