# Generated by Django 5.2.8 on 2025-11-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('descrip_Consulta', models.TextField(max_length=1200)),
                ('respuesta_consulta', models.TextField(blank=True, max_length=1200, null=True)),
                ('estado_consulta', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=100)),
                ('tiempo_respuesta', models.FloatField(blank=True, null=True)),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
