# Generated by Django 5.2.8 on 2025-12-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=70)),
                ('almacenamiento', models.CharField(max_length=70)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Compu_dañados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_daño', models.TextField(max_length=500)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('gravedad_daño', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=50)),
                ('estado_inicial', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Reparado', 'Reparado')], default='Pendiente', max_length=100)),
                ('ID_computador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Computadores.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_remocion', models.DateField(blank=True, null=True)),
                ('ID_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente')),
                ('ID_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computadores.computador')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('ID_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computadores.computador')),
            ],
        ),
    ]
